### PR TITLE
Revert "STRF-7025 remove jquery from stencil-utils"

### PR DESCRIPTION
**Pull request by jbruni**
This reverts commit 1543be8227eae6f5390e1c76db65aa0791ac5f7f.

Explanation at https://github.com/bigcommerce/stencil-utils/pull/110#issuecomment-586749147

It restores Cornerstone dynamic search results pagination functionality.

### CODE REVIEW

**Comment by bookernath** [comment]
Thanks as always @jbruni , will get the team looking at it tomorrow.

**Comment by jbruni** [comment]
Thanks, @bookernath 

Just found this issue reported at Cornerstone repository: https://github.com/bigcommerce/cornerstone/issues/1612

I believe this PR fixes that.

Or, in other words: that issue is a consequence of the side-effects from the commit which this PR reverts.

**Comment by jbruni** [comment]
This PR is really just an "appendix" of the "real deal" PR at https://github.com/bigcommerce/cornerstone/pull/1641

**Comment by jbruni** [comment]
Thanks for reviewing (and merging) so quickly.
Note that I agree with the idea of avoiding jquery as a dependency.
We just need to be more careful in the next removal attempt.

**Pull request merged**
